name: data-ingester
on:
  pull_request:
    paths: 
      - 'data-ingester/**'
      - '.github/workflows/data-ingester.yaml'
  push:
    branches:
      - main
    paths: 
      - 'data-ingester/**'
      - '.github/workflows/data-ingester.yaml'

defaults:
  run:
    working-directory: ./data-ingester

jobs:
  static-analysis:
    name: Static analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Linting
        uses: chartboost/ruff-action@v1
      - name: Formating
        uses: chartboost/ruff-action@v1
        with:
          args: 'format --check'